e_Prescription/Models/Account/Pharmacist.cs
using e_Prescription.Data;
using e_Prescription.Models.Validations;
using System.ComponentModel.DataAnnotations;

namespace e_Prescription.Models.Account
{
    public class Pharmacist
    {
        [Key]
        public int UserId { get; set; }

        [Required(ErrorMessage = "*Required")]
        [RegularExpression(@"^\d{6}$", ErrorMessage = "Invalid HPCSA Number Number")]
        public string PharmacyLicenseNumber { get; set; }

        [Required(ErrorMessage = "*Required")]
        [FutureDate(ErrorMessage = "The License Expiry Date must be a date in the future.")]
        public DateTime LicenseExpiryDate { get; set; }

        public ApplicationUser ApplicationUser { get; set; }
    }
}

e_Prescription/Models/Medication.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace e_Prescription.Models
{
    public class Medication
    {
        [Key]
        public int MedicationId { get; set; }

        [Required(ErrorMessage = "*Required")]
        public string MedicationName { get; set; }

        [Required(ErrorMessage = "*Required")]
        [ForeignKey("Dosage")]
        public int DosageFormId { get; set; }
        public virtual DosageForm DosageForm { get; set; }

        [Required(ErrorMessage = "*Required")]
        public string Schedule { get; set; }

        public virtual MedicationIngredient MedicationIngredient { get; set; }
    }
}

e_Prescription/Models/ViewPrescriptionViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;

namespace e_Prescription.Models
{
    public class ViewPrescriptionViewModel
    {
        public PrescriptionItem PrescriptionItem { get; set; }
        public SelectList StatusOptions { get; set; }

        public string AlertMessage { get; set; }
    }
}

e_Prescription/Controllers/PharmacistController.cs
using e_Prescription.Data;
using Microsoft.AspNetCore.Mvc;
using e_Prescription.Models.Account;
using e_Prescription.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.Build.ObjectModelRemoting;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Identity;
using System.Collections.Generic;
using System.Configuration;
using System.Text;
using iText.Kernel.Pdf;
using iText.Layout;
using iText.Layout.Element;
using e_Prescription.Models.ViewModels;
//using e_Prescription.Migrations;
using iText.Commons.Actions.Contexts;
//using e_Prescription.Migrations;



namespace e_Prescription.Controllers
{
    public class PharmacistController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IConfiguration _configuration; // Add IConfiguration as a field
        private readonly UserManager<ApplicationUser> _userManager;
        private string alertMessage;

        public PharmacistController(ApplicationDbContext context, IConfiguration configuration, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _configuration = configuration; // Assign IConfiguration
            _userManager = userManager;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Dashboard()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> UpdatePrescriptionStatus(int id)
        {
            var prescriptionItem = await _context.PrescriptionItems
        .Include(p => p.Prescription)
            .ThenInclude(p => p.Admission)
                .ThenInclude(a => a.Patient)
        .Include(p => p.Prescription)
            .ThenInclude(p => p.ApplicationUser)
        .Include(p => p.PharmacyMedication)
            .ThenInclude(pm => pm.PharmacyMedicationIngredients)
                .ThenInclude(pmi => pmi.ActiveIngredient)
        .FirstOrDefaultAsync(p => p.PrescriptionId == id);

            // Check if prescriptionItem or any necessary navigation property is null
            if (prescriptionItem == null ||
                prescriptionItem.PharmacyMedication == null ||
                prescriptionItem.Prescription?.Admission == null)
            {
                return NotFound();
            }

            // Retrieve patient's conditions
            var patientConditions = _context.PatientConditions
                .Where(pc => pc.PatientId == prescriptionItem.Prescription.Admission.PatientId)
                .Select(pc => pc.PatientConditionId)
                .ToList();

            // Retrieve medication ingredients
            var medIngredients = prescriptionItem.PharmacyMedication.PharmacyMedicationIngredients
                .Select(ma => ma.ActiveIngredient)
                .ToList();

            // Get a list of active ingredient IDs
            var activeIngredientIds = medIngredients
                .Where(mi => mi != null)
                .Select(mi => mi.ActiveIngredientId)
                .ToList();

            // Check for contraindications
            var contraindications = await _context.ContraIndications
                .Include(ci => ci.ActiveIngredient)
                .Include(ci => ci.ChronicCondition)
                .Where(ci => patientConditions.Contains(ci.ChronicConditionId) &&
                             activeIngredientIds.Contains(ci.ActiveIngredientId)) // Use Contains for matching IDs
                .Select(ci => ci.ActiveIngredient.IngredientName)
                .ToListAsync();

            // Prepare warning messages
            if (contraindications.Any())
            {
                var contraindicationWarning = $"There are contraindications for: {string.Join(", ", contraindications)}";
                TempData["ContraIndicationWarning"] = contraindicationWarning;
            }


            // Retrieve the patient's allergies (ActiveIngredientId)
            var patientAllergies = _context.PatientAllergies
                .Where(pa => pa.PatientId == prescriptionItem.Prescription.Admission.PatientId)
                .Select(pa => pa.ActiveIngredientId)
                .ToList();

            // Retrieve the active ingredients of the prescribed medication
            var medicationIngredients = prescriptionItem.PharmacyMedication.PharmacyMedicationIngredients
                .Select(ma => ma.ActiveIngredient)
                .ToList();

            // Find the ingredients that the patient is allergic to
            var allergicIngredients = medicationIngredients
                               .Where(mi => mi != null && patientAllergies.Contains(mi.ActiveIngredientId)) // Ensure mi is not null
                               .Select(mi => mi.IngredientName) // Get the name of the ingredient
                               .ToList();

            if (allergicIngredients.Any())
            {
                // Create a warning message with the names of the allergic ingredients
                var allergyWarning = $"This patient is allergic to: {string.Join(", ", allergicIngredients)}.";
                TempData["AllergyWarning"] = allergyWarning;
            }


            // Prepare a list of status options
            var statusOptions = new List<string> { "Pending", "Rejected", "Dispensed" };

            var viewModel = new ViewPrescriptionViewModel
            {
                PrescriptionItem = prescriptionItem,
                StatusOptions = new SelectList(statusOptions),
                AlertMessage = alertMessage // Pass the alert message to the view
            };

            return View(viewModel);
        }


        [HttpPost]
        public async Task<IActionResult> UpdatePrescriptionStatus(int id, string status, string rejectionReason)
        {
            if (string.IsNullOrEmpty(status))
            {
                ModelState.AddModelError(string.Empty, "Status is required.");
                var statusOptions = new List<string> { "Pending", "Rejected", "Dispensed" };

                // Fetch the prescription item again to repopulate the view model
                var prescriptionItem = await _context.PrescriptionItems
                    .Include(p => p.Prescription)
                        .ThenInclude(p => p.Admission)
                            .ThenInclude(a => a.Patient)
                    .Include(p => p.Prescription)
                        .ThenInclude(p => p.ApplicationUser)
                    .Include(p => p.PharmacyMedication)
                    .FirstOrDefaultAsync(p => p.PrescriptionId == id);

                if (prescriptionItem == null ||
                    prescriptionItem.PharmacyMedication == null ||
                    prescriptionItem.Prescription?.Admission == null)
                {
                    return NotFound(); // Prescription item or related data not found
                }


                var viewModel = new ViewPrescriptionViewModel
                {
                    PrescriptionItem = prescriptionItem,
                    StatusOptions = new SelectList(statusOptions),
                    AlertMessage = alertMessage // Pass the alert message to the view
                };

                return View(viewModel);
            }

            try
            {
                var prescriptionItemToUpdate = await _context.PrescriptionItems
                    .Include(p => p.Prescription)
                        .ThenInclude(p => p.Admission)
                            .ThenInclude(a => a.Patient)
                    .Include(p => p.PharmacyMedication) // Include PharmacyMedication to access medication detail
                    .FirstOrDefaultAsync(p => p.PrescriptionId == id);

                if (prescriptionItemToUpdate == null ||
                    prescriptionItemToUpdate.PharmacyMedication == null ||
                    prescriptionItemToUpdate.Prescription?.Admission == null)
                {
                    return NotFound(); // Prescription item or related data not found
                }


                if (!string.IsNullOrEmpty(alertMessage))
                {
                    // If there's an alert, display it to the user
                    ModelState.AddModelError(string.Empty, alertMessage);
                    return View(new ViewPrescriptionViewModel
                    {
                        PrescriptionItem = prescriptionItemToUpdate,
                        StatusOptions = new SelectList(new List<string> { "Pending", "Rejected", "Dispensed" }),
                        AlertMessage = alertMessage // Include the alert message in the view model
                    });
                }

                // Update the status
                prescriptionItemToUpdate.Prescription.Status = status;

                if (status == "Rejected")
                {
                    // Handle rejection reason, e.g., log it or save it as needed
                    prescriptionItemToUpdate.RejectionNote = rejectionReason; // Adjust this line as needed
                }

                if (status == "Dispensed")
                {
                    // Reduce stock only if the status is "Dispensed"
                    var medication = prescriptionItemToUpdate.PharmacyMedication;
                    if (medication != null)
                    {
                        // Assuming you have a Quantity property in PrescriptionItem representing the amount dispensed
                        var quantityDispensed = prescriptionItemToUpdate.Quantity;
                        if (medication.QuantityOnHand >= quantityDispensed)
                        {
                            medication.QuantityOnHand -= quantityDispensed;
                        }
                        else
                        {
                            // Handle the case where there's not enough stock

e_Prescription/Views/Pharmacist/Dashboard.cshtml
@{
    ViewData["Title"] = "Dashboard";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - e_Prescription</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/e_Prescription.styles.css" asp-append-version="true" />

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.14/css/bootstrap-select.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" />

    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.14/js/bootstrap-select.min.js"></script>
    <style>
        .dashboard {
            display: flex;
            flex-wrap: wrap;
            gap: 20px;
            margin-top: 20px; /* Add margin to create space between header and dashboard */
        }

        .align-left {
            align-items: flex-end;
            text-align: left;
        }

        .btn1 {
            margin-top: 20px;
            margin-bottom: 5px;
        }

        .header {
            text-align: center;
            margin-top: 40px;
            margin-bottom: 20px;
            width: 100%; /* Ensure the header spans the entire width */
        }

            .header h1 {
                font-size: 36px;
                font-family: fantasy;
                color: #28a745;
                margin-bottom: 5px;
            }

        .date {
            font-size: 18px;
            color: #555;
        }

        .card-container {
            display: flex;
            justify-content: space-around;
            margin-top: 20px;
        }

        .card {
            display: flex;
            align-items: center;
            background-color: darkgreen;
            border-radius: 8px;
            box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.1);
            padding: 20px;
            width: 250px;
            transition: box-shadow 0.3s ease;
        }

            .card:hover {
                box-shadow: 0px 8px 16px rgba(0, 0, 0, 0.2);
            }

        .icon {
            font-size: 30px;
            color: brown;
            margin-right: 15px;
        }

        .divider-horizontal {
            width: 80%; /* Adjust width as needed */
            height: 1px;
            background-color: #ccc; /* Line color */
            margin-bottom: 15px; /* Space between the line and the text */
        }

        .card-name {
            font-size: 18px;
            font-weight: bold;
            color: white;
            text-decoration:none;
        }

            .card-name:hover {
                text-decoration: underline; /* Add underline on hover */
                color: #28a745; /* Change color on hover for better user feedback */

    </style>
</head>

<div class="header">
    <h1>Welcome</h1>
    <h1>To</h1>
    <h1>Bay Breeze Day Hospital</h1>
    <p class="date">August 25, 2024</p> <!-- Update dynamically for today's date -->
</div>
<div class="card-container">
    <div class="card">
        <div class="icon">           
            <i class="fas fa-prescription"></i>
        </div>
        <div class="divider-horizontal"></div> <!-- This is the horizontal line divider -->
        <a href ="@Url.Action("GetPrescriptions", "Pharmacist")" class="card-name">
            Prescriptions
        </a>
    </div>
    <div class="card">
        <div class="icon">
            <i class="fas fa-pills"></i>
        </div>
        <div class="divider-horizontal"></div> <!-- This is the horizontal line divider -->
        <a href="@Url.Action("MedicationList","Pharmacist")" class="card-name">
            Medications
        </a>
    </div>
    <div class="card">
        <div class="icon">
            <i class="fas fa-capsules"></i>
        </div>
        <div class="divider-horizontal"></div> <!-- This is the horizontal line divider -->
        <a href="@Url.Action("AddMedication","Pharmacist")" class="card-name">
            Add Medications
        </a>
    </div>
</div>
<div class="card-container">    
    <div class="card">
        <div class="icon">
            <i class="fas fa-clipboard"></i>
        </div>
        <div class="divider-horizontal"></div> <!-- This is the horizontal line divider -->
        <a href="@Url.Action("OrderMedications","Pharmacist")" class="card-name">
            Stock Order
        </a>
    </div>
    <div class="card">
        <div class="icon">
            <i class="fas fa-check"></i>
        </div>
        <div class="divider-horizontal"></div> <!-- This is the horizontal line divider -->
        <a href="@Url.Action("ReceivedMedicationRecords","Pharmacist")" class="card-name">
            Stock Received
        </a>
    </div>
    <div class="card">
        <div class="icon">
            <i class="fas fa-file-import"></i>
        </div>
        <div class="divider-horizontal"></div> <!-- This is the horizontal line divider -->
        <a href="@Url.Action("ReceivedMedication","Pharmacist")" class="card-name">
            Capture Stock
        </a>
    </div>
</div>
<div class="card-container">
    <div class="card">
        <div class="icon">
            <i class="fas fa-file"></i>
        </div>
        <div class="divider-horizontal"></div> <!-- This is the horizontal line divider -->
        <a href="@Url.Action("SearchPrescriptions","Pharmacist")" class="card-name">
            Dispensary Report
        </a>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

    <script>
        function openDashboardModal(url) {
            $('#DashboardModalBody').load(url, function () {
                $('#DashboardModal').modal('show');
            });
        }
    </script>
}

e_Prescription/Views/Pharmacist/GenerateDispensaryReport.cshtml
@model PDispensaryReportViewModel

@{
    ViewData["Title"] = "Generate Dispensary Report";
}

<div class="col-md-12 mx-auto pt-0 p-0">
    <div class="form-card" id="card-content">
        <div class="card-header bg-success text-uppercase text-white" style="height: 45px;">
            <h4 class="text-center">Dispensary Report</h4>
        </div>
        <br />
        <p class="d-flex justify-content-center"><strong>Pharmacist:&ensp; </strong> @Model.PharmacistName</p>

       @*  <!-- Date Range Selection Form -->
        <form method="get" action="@Url.Action("GenerateDispensaryReport", "Pharmacist")" style="width: 50%;">
            <div class="form-group" style="margin-bottom: 10px;">
                <label for="startDate" style="font-size: 16px; font-weight: bold; display: inline-block; width: 100px;">Start Date:</label>
                <input type="date" id="startDate" name="startDate" class="form-control" value="@Model.StartDate.ToString("yyyy-MM-dd")" style="font-size: 16px; padding: 5px; width: 150px; height: 30px; display: inline-block;" />
            </div>
            <div class="form-group" style="margin-bottom: 10px;">
                <label for="endDate" style="font-size: 16px; font-weight: bold; display: inline-block; width: 100px;">End Date:</label>
                <input type="date" id="endDate" name="endDate" class="form-control" value="@Model.EndDate.ToString("yyyy-MM-dd")" style="font-size: 16px; padding: 5px; width: 150px; height: 30px; display: inline-block;" />
            </div>
            <button type="submit" class="btn btn-warning btn-sm">Generate Report</button>
            <div class="d-flex justify-content-end mt-2">
                <button type="button" onclick="downloadPDF()" class="btn btn-danger btn-sm">
                    <!-- Changed to red -->
                    <i class="fas fa-download"></i> Download PDF
                </button>
            </div>
        </form> *@

        <div class="row">
            <div class="col-md-6 d-flex justify-content-start">
                <p><strong>Date Range:</strong> @Model.StartDate.ToString("dd MMMM yyyy") - @Model.EndDate.ToString("dd MMMM yyyy")</p>
            </div>
            <div class="col-md-6 d-flex justify-content-end">
                <p><strong>Report Generated:</strong> @DateTime.Now.ToString("dd MMMM yyyy")</p>
            </div>
        </div>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Patient</th>
                    <th>Script By</th>
                    <th>Medication</th>
                    <th>Quantity</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var prescription in Model.Prescriptions)
                {
                    <tr>
                        <td>@prescription.Prescription?.Date.ToString("dd MMM yyyy")</td>
                        <td>@prescription.Prescription?.Admission?.Patient?.Firstname </td>
                        <td>Dr. @prescription.Prescription?.ApplicationUser?.FirstName @prescription.Prescription?.ApplicationUser?.LastName </td>
                        <td>@prescription.PharmacyMedication?.MedicationName </td>
                        <td>@prescription.Quantity</td>
                        <td>@prescription.Prescription?.Status </td>
                    </tr>
                }
            </tbody>
        </table>

        <p><strong>Total Scripts Dispensed:</strong> @Model.TotalDispensed</p>
        <p><strong>Total Scripts Rejected:</strong> @Model.TotalRejected</p>
        <br />
        <p class="fw-bold" style="font-size:20px">SUMMARY PER MEDICATION:</p>
        <table class="table table-striped" style="width: 50%; font-size: 16px; padding: 5px;">
            <thead>
                <tr>
                    <th style="padding: 5px;">Medication</th>
                    <th style="padding: 5px;">Quantity Dispensed</th>
                </tr>
            </thead>
            <tbody>
                @if (Model.SummaryPerMedication.Any())
                {
                    foreach (var item in Model.SummaryPerMedication)
                    {
                        <tr>
                            <td style="padding: 5px;">@item.Medication</td>
                            <td style="padding: 5px;">@item.QuantityDispensed</td>
                        </tr>
                    }
                }
                else
                {
                    <tr>
                        <td colspan="2" class="text-center">No summary available for the selected date range.</td>
                    </tr>
                }
            </tbody>
        </table>
        <div class="d-flex justify-content-end mt-2">
            <button type="button" onclick="downloadPDF()" class="btn btn-danger btn-sm">
                <!-- Changed to red -->
                <i class="fas fa-download"></i> Download PDF
            </button>
        </div>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

    <script src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.10.1/html2pdf.bundle.min.js"></script>
    <script>
        function downloadPDF() {
            const element = document.getElementById('card-content');
            html2pdf()
                .from(element)
                .save('patient_admission.pdf')
                .catch(err => {
                    console.error("Error generating PDF:", err);
                });
        }
    </script>
}

e_Prescription/Views/Pharmacist/GetPrescriptions.cshtml
@model IEnumerable<e_Prescription.Models.PrescriptionItem>

@{
    ViewData["Title"] = "Prescriptions";
}

<style>
    .dashboard {
        display: flex;
        flex-wrap: wrap;
        gap: 20px;
        margin-top: 20px; /* Add margin to create space between header and dashboard */
    }

    .align-left {
        align-items: flex-end;
        text-align: left;
    }

    .btn1 {
        margin-top: 20px;
        margin-bottom: 5px;
    }

</style>
<div class="col-md-12 mx-auto pt-0 p-0">
    <div class="card">
        <div class="card-header bg-success text-uppercase text-white" style="height: 45px;">
            <h4 class="text-center">Manage Prescriptions</h4>
        </div>       

        @if (TempData["SuccessMessage"] != null)
        {
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                @TempData["SuccessMessage"]
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        }

        <div class="col-md-12 d-flex justify-content-end mt-3">
            <!-- Urgent Filter Form -->
            <form method="get" action="@Url.Action("GetPrescriptions", "Pharmacist")">
                <div class="form-group">
                    <input type="checkbox" id="showUrgentOnly" name="showUrgentOnly" value="true" @(ViewBag.ShowUrgentOnly ? "checked" : "") />
                    <label for="showUrgentOnly">Show only urgent prescriptions</label>
                </div>
                <div class="form-group">
                    <input type="checkbox" id="showPendingOnly" name="showPendingOnly" value="true" @(ViewBag.ShowPendingOnly ? "checked" : "") />
                    <label for="showPendingOnly">Show only prescribed prescriptions</label>
                </div>
                <button type="submit" class="btn btn-danger btn-sm">Filter</button>
            </form>
        </div>



        <table class="table table-striped">
            <thead>
                <tr>   
                    <th>
                        Date
                    </th>
                    <th>
                        Patient Name
                    </th>
                    <th>
                        Surgeon Name
                    </th>                                      
                    <th>
                        Medication Name
                    </th>
                    <th>
                        Quantity
                    </th>
                    <th>
                        Status
                    </th> 
                    <th>
                        Urgency
                    </th>
                    <th>
                        Rejection Note
                    </th>
                    <th>
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @item.Prescription.PresciptionDate.ToShortDateString()
                        </td>
                        <td>
                            @item.Prescription.Admission.Patient.Firstname
                        </td>
                        <td>
                            Dr. @item.Prescription.ApplicationUser.FirstName @item.Prescription.ApplicationUser.LastName
                        </td>
                        <td>
                            @item.PharmacyMedication.MedicationName
                        </td>
                        <td>
                            @item.Quantity
                        </td>
                        
                        <td>
                            @item.Prescription.Status
                        </td>
                        <td>
                            @if (item.Prescription.IsUrgent)
                            {
                                <span class="badge badge-danger">Urgent</span>
                            }
                            else
                            {
                                <span>Not Urgent</span>
                            }
                        </td>
                        <td>
                            @item.RejectionNote
                        </td>

                        <td>
                            <a class="btn btn-info" href="@Url.Action("UpdatePrescriptionStatus", "Pharmacist", new { id = item.PrescriptionId })">Update</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
</div>
    

e_Prescription/Views/Pharmacist/ManageStock.cshtml
@model e_Prescription.Models.PharmacyMedication

@{
    ViewData["Title"] = "Order medication";
    Layout = "_Layout2";
}

<style>
    .centered-container {
        display: flex;
        justify-content: center;
        align-items: center;
        margin-top: 20px;
        width: 100%;
    }

    .btn-group {
        display: flex;
        justify-content: space-between;
        width: 100%;
        gap: 30px;
    }
</style>

<div class="row">
    <div class="col-md-10">
        <form asp-action="ManageStock" method="post">
            <input type="hidden" asp-for="PharmacyMedicationId" />
            <div>
                <label>Medication: @Model.MedicationName</label>
            </div>
            <div>
                <label>Current Quantity: @Model.QuantityOnHand</label>
            </div>
            <div>
                <label>Order Quantity</label>
                <input type="number" name="orderQuantity" min="1" required />
            </div>
            <button type="submit" class="btn btn-primary">Order</button>
        </form>
    </div>
</div>

e_Prescription/Views/Pharmacist/ReceivedMedication.cshtml
@model e_Prescription.Models.ReceivedOrderViewModel // Update with your actual namespace

@{
    ViewData["Title"] = "Add Received Medication";
}

@* <h1>Add Received Medication</h1> *@

<div class="col-md-12 mx-auto pt-0 p-0">
    <div class="card">
        <div class="card-header bg-success text-uppercase text-white" style="height: 45px;">
            <h4 class="text-center">Add Received Medication</h4>
        </div>

        <div class="card-body">
            <div class="container">
                <div class="row justify-content-center">
                     <form asp-action="ReceivedMedication" method="post">
                        <div class="form-group">
                            <label asp-for="SelectedMedicationId">Medication</label>
                            <select asp-for="SelectedMedicationId" asp-items="Model.Medications" class="form-control">
                            <option value="">Select Medication</option>
                            </select>
                            <span asp-validation-for="SelectedMedicationId" class="text-danger"></span>
                        </div>

                        <div class="form-group">
                            <label asp-for="QuantityReceived">Quantity Received</label>
                            <input type="number" asp-for="QuantityReceived" class="form-control" />
                            <span asp-validation-for="QuantityReceived" class="text-danger"></span>
                        </div>

                        <button type="submit" class="btn btn-primary">Capture</button>
                        <a href="@Url.Action("ReceivedMedicationRecords", "Pharmacist")" class="btn btn-secondary ml-2">Back</a>
                    </form>
                </div>
            </div>
         </div>
    </div>
</div>